"""empty message

Revision ID: 1b45ad923d11
Revises: 8715b74479de
Create Date: 2021-09-23 11:33:19.390741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b45ad923d11'
down_revision = '8715b74479de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('film51', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film52', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film53', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film54', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film55', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film56', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film57', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film58', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film59', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film60', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'film60')
    op.drop_column('user', 'film59')
    op.drop_column('user', 'film58')
    op.drop_column('user', 'film57')
    op.drop_column('user', 'film56')
    op.drop_column('user', 'film55')
    op.drop_column('user', 'film54')
    op.drop_column('user', 'film53')
    op.drop_column('user', 'film52')
    op.drop_column('user', 'film51')
    # ### end Alembic commands ###
