"""empty message

Revision ID: 40c02135bb30
Revises: 5a0015fd591e
Create Date: 2021-09-24 19:43:18.440907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c02135bb30'
down_revision = '5a0015fd591e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('film91', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film92', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film93', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film94', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film95', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film96', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film97', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film98', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film99', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film100', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'film100')
    op.drop_column('user', 'film99')
    op.drop_column('user', 'film98')
    op.drop_column('user', 'film97')
    op.drop_column('user', 'film96')
    op.drop_column('user', 'film95')
    op.drop_column('user', 'film94')
    op.drop_column('user', 'film93')
    op.drop_column('user', 'film92')
    op.drop_column('user', 'film91')
    # ### end Alembic commands ###
