"""empty message

Revision ID: 48d05ef76565
Revises: 5dd5fa0ad63f
Create Date: 2021-10-14 11:38:36.852962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d05ef76565'
down_revision = '5dd5fa0ad63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moovie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moovie', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('moovie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'moovie', ['moovie_id'], ['id'])
    op.drop_column('post', 'moovie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('moovie', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'moovie_id')
    op.drop_table('moovie')
    # ### end Alembic commands ###
