"""empty message

Revision ID: 69baae89633f
Revises: 28887dc8b86a
Create Date: 2021-09-15 10:05:17.245348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69baae89633f'
down_revision = '28887dc8b86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('film21', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film22', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film23', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film24', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film25', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film26', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film27', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film28', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film29', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film30', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'film30')
    op.drop_column('user', 'film29')
    op.drop_column('user', 'film28')
    op.drop_column('user', 'film27')
    op.drop_column('user', 'film26')
    op.drop_column('user', 'film25')
    op.drop_column('user', 'film24')
    op.drop_column('user', 'film23')
    op.drop_column('user', 'film22')
    op.drop_column('user', 'film21')
    # ### end Alembic commands ###
