"""empty message

Revision ID: 8715b74479de
Revises: 69baae89633f
Create Date: 2021-09-15 18:07:34.551668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8715b74479de'
down_revision = '69baae89633f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('film31', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film32', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film33', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film34', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film35', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film36', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film37', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film38', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film39', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film40', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film41', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film42', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film43', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film44', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film45', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film46', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film47', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film48', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film49', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film50', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'film50')
    op.drop_column('user', 'film49')
    op.drop_column('user', 'film48')
    op.drop_column('user', 'film47')
    op.drop_column('user', 'film46')
    op.drop_column('user', 'film45')
    op.drop_column('user', 'film44')
    op.drop_column('user', 'film43')
    op.drop_column('user', 'film42')
    op.drop_column('user', 'film41')
    op.drop_column('user', 'film40')
    op.drop_column('user', 'film39')
    op.drop_column('user', 'film38')
    op.drop_column('user', 'film37')
    op.drop_column('user', 'film36')
    op.drop_column('user', 'film35')
    op.drop_column('user', 'film34')
    op.drop_column('user', 'film33')
    op.drop_column('user', 'film32')
    op.drop_column('user', 'film31')
    # ### end Alembic commands ###
