"""film1, film2

Revision ID: 97d66906f0e0
Revises: ca57d65b1699
Create Date: 2019-05-23 20:16:56.620353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d66906f0e0'
down_revision = 'ca57d65b1699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('film1', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('film2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'film2')
    op.drop_column('user', 'film1')
    # ### end Alembic commands ###
