"""moovies table

Revision ID: c1a09adcaf57
Revises: bd4d7fd10ae5
Create Date: 2019-06-12 05:28:10.375510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a09adcaf57'
down_revision = 'bd4d7fd10ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moovies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb', sa.String(length=140), nullable=True),
    sa.Column('poster', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moovies')
    # ### end Alembic commands ###
